apiVersion: v1
kind: Pod
metadata:
  name: all-pod
spec:
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: pv-claim
  containers:
  - name: apache
    image: brianbaugher/daily-bugle:apache 
    ports:
    - containerPort: 80
      name: "apache"
  - name: article
    image: brianbaugher/daily-bugle:article
    ports:
    - containerPort: 3011
      name: "article"
  - name: ad
    image: brianbaugher/daily-bugle:ad
    ports:
    - containerPort: 3012
      name: "ad"
  - name: auth
    image: brianbaugher/daily-bugle:auth
    ports:
    - containerPort: 3013
      name: "auth"
  - name: mongo
    image: mongo 
    ports:
      - containerPort: 27017
        name: "mongo"
    volumeMounts:
      - mountPath: "/data/db"
        name: pv-storage
